<template>
<li class="flex flex-col">
  <label class="text-color-form" :for="param">{{ $t(param) }}</label>

  <div class="col-span-3 relative z-0">
    <select v-model="model" class="appearance-none block w-full rounded border form-border-color focus:outline-none p-2 mt-2">
      <option v-if="!['circleColor'].includes(param)" v-for="v, index in getItems(param)" :key="index" :value="v">{{ v }}</option>
      <option v-if="['circleColor'].includes(param)" v-for="v, index in getItems(param)" :key="index" :value="v[0]">{{ v[1] }}</option>
    </select>
    <div class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 mt-2 text-color-nav">
      <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
        <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
      </svg>
    </div>
  </div>
</li>
</template>

<script>
export default {
  data() {
    return {
      circleColor: [
        ['#F0F8FF', 'AliceBlue'],
        ['#FAEBD7', 'AntiqueWhite'],
        ['#00FFFF', 'Aqua'],
        ['#7FFFD4', 'Aquamarine'],
        ['#F0FFFF', 'Azure'],
        ['#F5F5DC', 'Beige'],
        ['#FFE4C4', 'Bisque'],
        ['#000000', 'Black'],
        ['#FFEBCD', 'BlanchedAlmond'],
        ['#0000FF', 'Blue'],
        ['#8A2BE2', 'BlueViolet'],
        ['#A52A2A', 'Brown'],
        ['#DEB887', 'BurlyWood'],
        ['#5F9EA0', 'CadetBlue'],
        ['#7FFF00', 'Chartreuse'],
        ['#D2691E', 'Chocolate'],
        ['#FF7F50', 'Coral'],
        ['#6495ED', 'CornflowerBlue'],
        ['#FFF8DC', 'Cornsilk'],
        ['#DC143C', 'Crimson'],
        ['#00FFFF', 'Cyan'],
        ['#00008B', 'DarkBlue'],
        ['#008B8B', 'DarkCyan'],
        ['#B8860B', 'DarkGoldenrod'],
        ['#A9A9A9', 'DarkGray'],
        ['#006400', 'DarkGreen'],
        ['#BDB76B', 'DarkKhaki'],
        ['#8B008B', 'DarkMagenta'],
        ['#556B2F', 'DarkOliveGreen'],
        ['#FF8C00', 'DarkOrange'],
        ['#9932CC', 'DarkOrchid'],
        ['#8B0000', 'DarkRed'],
        ['#E9967A', 'DarkSalmon'],
        ['#8FBC8B', 'DarkSeaGreen'],
        ['#483D8B', 'DarkSlateBlue'],
        ['#2F4F4F', 'DarkSlateGray'],
        ['#00CED1', 'DarkTurquoise'],
        ['#9400D3', 'DarkViolet'],
        ['#FF1493', 'DeepPink'],
        ['#00BFFF', 'DeepSkyBlue'],
        ['#696969', 'DimGray'],
        ['#1E90FF', 'DodgerBlue'],
        ['#B22222', 'FireBrick'],
        ['#FFFAF0', 'FloralWhite'],
        ['#228B22', 'ForestGreen'],
        ['#FF00FF', 'Fuchsia'],
        ['#DCDCDC', 'Gainsboro'],
        ['#F8F8FF', 'GhostWhite'],
        ['#FFD700', 'Gold'],
        ['#DAA520', 'Goldenrod'],
        ['#808080', 'Gray'],
        ['#008000', 'Green'],
        ['#ADFF2F', 'GreenYellow'],
        ['#F0FFF0', 'HoneyDew'],
        ['#FF69B4', 'HotPink'],
        ['#CD5C5C', 'IndianRed'],
        ['#4B0082', 'Indigo'],
        ['#FFFFF0', 'Ivory'],
        ['#F0E68C', 'Khaki'],
        ['#E6E6FA', 'Lavender'],
        ['#FFF0F5', 'LavenderBlush'],
        ['#7CFC00', 'LawnGreen'],
        ['#FFFACD', 'LemonChiffon'],
        ['#ADD8E6', 'LightBlue'],
        ['#F08080', 'LightCoral'],
        ['#E0FFFF', 'LightCyan'],
        ['#FAFAD2', 'LightGoldenrodYellow'],
        ['#D3D3D3', 'LightGray'],
        ['#90EE90', 'LightGreen'],
        ['#FFB6C1', 'LightPink'],
        ['#FFA07A', 'LightSalmon'],
        ['#FFA07A', 'LightSalmon'],
        ['#20B2AA', 'LightSeaGreen'],
        ['#87CEFA', 'LightSkyBlue'],
        ['#778899', 'LightSlateGray'],
        ['#B0C4DE', 'LightSteelBlue'],
        ['#FFFFE0', 'LightYellow'],
        ['#00FF00', 'Lime'],
        ['#32CD32', 'LimeGreen'],
        ['#FAF0E6', 'Linen'],
        ['#FF00FF', 'Magenta'],
        ['#800000', 'Maroon'],
        ['#66CDAA', 'MediumAquamarine'],
        ['#0000CD', 'MediumBlue'],
        ['#BA55D3', 'MediumOrchid'],
        ['#9370DB', 'MediumPurple'],
        ['#3CB371', 'MediumSeaGreen'],
        ['#7B68EE', 'MediumSlateBlue'],
        ['#7B68EE', 'MediumSlateBlue'],
        ['#00FA9A', 'MediumSpringGreen'],
        ['#48D1CC', 'MediumTurquoise'],
        ['#C71585', 'MediumVioletRed'],
        ['#F5FFFA', 'MintCream'],
        ['#FFE4E1', 'MistyRose'],
        ['#FFE4B5', 'Moccasin'],
        ['#FFDEAD', 'NavajoWhite'],
        ['#000080', 'Navy'],
        ['#FDF5E6', 'OldLace'],
        ['#808000', 'Olive'],
        ['#6B8E23', 'OliveDrab'],
        ['#FFA500', 'Orange'],
        ['#FF4500', 'OrangeRed'],
        ['#DA70D6', 'Orchid'],
        ['#EEE8AA', 'PaleGoldenrod'],
        ['#98FB98', 'PaleGreen'],
        ['#AFEEEE', 'PaleTurquoise'],
        ['#DB7093', 'PaleVioletRed'],
        ['#FFEFD5', 'PapayaWhip'],
        ['#FFDAB9', 'PeachPuff'],
        ['#CD853F', 'Peru'],
        ['#FFC0CB', 'Pink'],
        ['#DDA0DD', 'Plum'],
        ['#B0E0E6', 'PowderBlue'],
        ['#800080', 'Purple'],
        ['#663399', 'RebeccaPurple'],
        ['#FF0000', 'Red'],
        ['#BC8F8F', 'RosyBrown'],
        ['#4169E1', 'RoyalBlue'],
        ['#8B4513', 'SaddleBrown'],
        ['#FA8072', 'Salmon'],
        ['#F4A460', 'SandyBrown'],
        ['#2E8B57', 'SeaGreen'],
        ['#FFF5EE', 'SeaShell'],
        ['#A0522D', 'Sienna'],
        ['#C0C0C0', 'Silver'],
        ['#87CEEB', 'SkyBlue'],
        ['#6A5ACD', 'SlateBlue'],
        ['#708090', 'SlateGray'],
        ['#FFFAFA', 'Snow'],
        ['#00FF7F', 'SpringGreen'],
        ['#4682B4', 'SteelBlue'],
        ['#D2B48C', 'Tan'],
        ['#008080', 'Teal'],
        ['#D8BFD8', 'Thistle'],
        ['#FF6347', 'Tomato'],
        ['#40E0D0', 'Turquoise'],
        ['#EE82EE', 'Violet'],
        ['#F5DEB3', 'Wheat'],
        ['#FFFFFF', 'White'],
        ['#F5F5F5', 'WhiteSmoke'],
        ['#FFFF00', 'Yellow'],
        ['#9ACD32', 'YellowGreen']
      ],
      clotheColor: [
        'Black',
        'Blue01',
        'Blue02',
        'Blue03',
        'Gray01',
        'Gray02',
        'Heather',
        'PastelBlue',
        'PastelGreen',
        'PastelOrange',
        'PastelRed',
        'PastelYellow',
        'Pink',
        'Red',
        'White'
      ],
      graphicType: [
        'Bat',
        'Cumbia',
        'Deer',
        'Diamond',
        'Hola',
        'Pizza',
        'Resist',
        'Selena',
        'Bear',
        'SkullOutline',
        'Skull'
      ],
      facialHairColor: [
        'Auburn',
        'Black',
        'Blonde',
        'BlondeGolden',
        'Brown',
        'BrownDark',
        'Platinum',
        'Red'
      ],
      facialHairType: [
        'Blank',
        'BeardMedium',
        'BeardLight',
        'BeardMajestic',
        'MoustacheFancy',
        'MoustacheMagnum'
      ],
      skinColor: [
        'Tanned',
        'Yellow',
        'Pale',
        'Light',
        'Brown',
        'DarkBrown',
        'Black'
      ],
      mouthType: [
        'Concerned',
        'Default',
        'Disbelief',
        'Eating',
        'Grimace',
        'Sad',
        'ScreamOpen',
        'Serious',
        'Smile',
        'Tongue',
        'Twinkle',
        'Vomit'
      ],
      eyeType: [
        'Close',
        'Cry',
        'Default',
        'Dizzy',
        'EyeRoll',
        'Happy',
        'Hearts',
        'Side',
        'Squint',
        'Surprised',
        'Wink',
        'WinkWacky'
      ],
      clotheType: [
        'BlazerShirt',
        'BlazerSweater',
        'CollarSweater',
        'GraphicShirt',
        'Hoodie',
        'Overall',
        'ShirtCrewNeck',
        'ShirtScoopNeck',
        'ShirtVNeck'
      ],
      eyebrowType: [
        'Angry',
        'AngryNatural',
        'Default',
        'DefaultNatural',
        'FlatNatural',
        'RaisedExcited',
        'RaisedExcitedNatural',
        'SadConcerned',
        'SadConcernedNatural',
        'UnibrowNatural',
        'UpDown',
        'UpDownNatural'
      ],
      accessoriesType: [
        'Blank',
        'Kurt',
        'Prescription01',
        'Prescription02',
        'Round',
        'Sunglasses',
        'Wayfarers'
      ],
      hairColor: [
        'Red',
        'Auburn',
        'Black',
        'Blonde',
        'BlondeGolden',
        'Brown',
        'BrownDark',
        'PastelPink',
        'Platinum',
        'SilverGray'
      ],
      topColor: [
        'Black',
        'Blue01',
        'Blue02',
        'Blue03',
        'Gray01',
        'Gray02',
        'Heather',
        'PastelBlue',
        'PastelGreen',
        'PastelOrange',
        'PastelRed',
        'PastelYellow',
        'Pink',
        'Red',
        'White'
      ],
      topType: [
        'NoHair',
        'Eyepatch',
        'Hat',
        'Hijab',
        'Turban',
        'WinterHat1',
        'WinterHat2',
        'WinterHat3',
        'WinterHat4',
        'LongHairBigHair',
        'LongHairBob',
        'LongHairBun',
        'LongHairCurly',
        'LongHairCurvy',
        'LongHairDreads',
        'LongHairFrida',
        'LongHairFro',
        'LongHairFroBand',
        'LongHairNotTooLong',
        'LongHairShavedSides',
        'LongHairMiaWallace',
        'LongHairStraight',
        'LongHairStraight2',
        'LongHairStraightStrand',
        'ShortHairDreads01',
        'ShortHairDreads02',
        'ShortHairFrizzle',
        'ShortHairShaggyMullet',
        'ShortHairShortCurly',
        'ShortHairShortFlat',
        'ShortHairShortRound',
        'ShortHairShortWaved',
        'ShortHairSides',
        'ShortHairTheCaesar',
        'ShortHairTheCaesarSidePart'
      ]
    }
  },
  props: ['param', 'value'],
  watch: {
    model: function() {
      this.$store.commit(`update${this.object.charAt(0).toUpperCase()}${this.object.substr(1)}`, this.model)
    }
  },
  computed: {
    object() {
      return this.$props.param
    },
    model: {
      get() {
        return this.$props.value
      },
      set(value) {
        this.$emit('data', value)
      }
    }
  },
  methods: {
    getItems(item) {
      return this[item]
    }
  }
}
</script>
